title: Alonzo
description: >
  Alonzo is a Java software project to code a Lambda Calculus interpreter.
  Alongside the code lives this blog dedicated to writing and teaching about
  what goes into writing the interpreter, and interesting coding choices.
baseurl: "/alonzo-java"
url: ""

markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

exclude: [Makefile, .gitignore]
keep_files: [.git, LICENSE_CONTENT, LICENSE_THEME, .gitignore, .nojekyll]
